### ISSUE TITLE
A bunch of remarks and suggestions

### ISSUE THREAD

**Issue by fingolfin** [HereAround/JToric#14]
Thank you for working on this! I have some minor feedback, after just browsing your source code. Some of them may be nonsense or won't work, as I only read the code, did not try any o this.

1. why `export CapAndHomalg` and `export GAP`?
1. why do you sometimes write `CapAndHomalg.GAP.Globals` instead of `GAP.Globals`?
1. in particular `CapAndHomalg.GAP.Globals.ConvertJuliaToGAP(foobar)` seems odd -- I suggest to instead call `julia_to_gap(foobar)` or even better, `GapObj(foobar)`
1. similarly, don't call `GAP.Globals.GAPToJulia`, use `gap_to_julia` instead -- or even better, if you know the result type, then use that. I.e. if `x` is a GAP string, then it's better to write `String(x)` than `gap_to_julia(x)`, as that allows for reliable type inference, makes the code easier to understand, and adds a layer of protection against mistakes
1. most (all?) of your structs lack type annotations, so everything is stored as `Any`. That prevents optimizations and may also waste storage. Type annotations also help people reading your code to understand it better, and of course they help catch some errors
1. your code formatting is a bit weird. Why does each function start and end with an empty line?
1. the names you export do not conform to Julia / Oscar naming guidelines: `IsCartier` should be `iscartier`, etc.
1. why do many (all?) of your structs have an unused member `bar`?
1. I recommend replacing `Array{T,1}` with the equivalent `Vector{T}`.
1. we just released Oscar.jl 0.6.0, so you may want to adjust your `Project.toml` accordingly

Regarding the conversion functions, it may also help to use that GAP.jl can convert things recursively. For example, let's look at this function:
```julia
function ListOfVariablesOfCoxRing( v::JToricVariety,  )
    
    gap_variables = CapAndHomalg.GAP.Globals.ListOfVariablesOfCoxRing( v.GapToricVariety )
    len = GAP.Globals.GAPToJulia( GAP.Globals.Length( gap_variables ) )
    julia_variables = [  GAP.Globals.GAPToJulia( gap_variables[ i ] ) for i in 1:len ]
    return julia_variables
    
end
```
I think it could be rewritten to something like this (but I did not verify this; and I only *guessed* a what type those `gap_variable[i]` are supposed to have):
```julia
function ListOfVariablesOfCoxRing(v::JToricVariety)
    vars = CapAndHomalg.GAP.Globals.ListOfVariablesOfCoxRing(v.GapToricVariety)
    return Vector{String}(vars)
end
```

Or for another example, consider this:
```julia
function IsProductOf( v::JToricVariety )
    
    factors = CapAndHomalg.GAP.Globals.IsProductOf( v.GapToricVariety )
    len = GAP.Globals.GAPToJulia( GAP.Globals.Length( factors ) )
    j_factors = [ JToricVariety( 1, factors[ i ] ) for i in 1:len ]
    return j_factors
    
end
```
It should be possible to rewrite this as follows:
```julia
function IsProductOf(v::JToricVariety)
    factors = CapAndHomalg.GAP.Globals.IsProductOf(v.GapToricVariety)
    return [ JToricVariety( 1, f ) for f in factors ]
end
```

**Comment by HereAround** [comment]
@fingolfin Thank you for the detailed feedback.

Most of this is because I am just starting to learn `Julia`. I'll try out your suggestions and make them into one (or more likely several) PRs. I will notify you to check on the changes.

**Comment by HereAround** [comment]
@fingolfin Thank you! Your comments are indeed very valuable. Please have a look at https://github.com/HereAround/JToric/pull/15. This PR aims to address all of the points raised above.

A separate PR with a few other general points is open: https://github.com/HereAround/JToric/issues/16. I am particularly uncertain about the first three. Suggestions/advice very much appreciated.

**Comment by HereAround** [comment]
@fingolfin - Can this be closed, or did I miss any of the points raised above?
